version: '3'

services:
  database:
    image: 'mongo'
    container_name: 'mongodb-container'
    environment:
      - MONGO_INITDB_DATABASE=cities
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro means you want to copy init-mongo.js to /docker-entrypoint-initdb.d/ as a read only file. /docker-entrypoint-initdb.d is a folder that already created inside the mongo container used for initiating database, so we copy our script to that folder
      - ./mongo-volume:/data/db # ./mongo-volume:/data/db means you want to set data on container persist on your local folder named mongo-volume . /data/db/ is a folder that already created inside the mongo container.
    ports:
      - '27017-27019:27017-27019'